### PR TITLE
Rotating File Names

### PR DESCRIPTION
**Pull request by jamesmcnamara**
@chasdevs Haven't tested it, but this should be all that's needed to get cache busters.

### CODE REVIEW

**Comment by chasdevs** [comment]
Ha! I think you're right. I was hoping it would be this easy. Are you all set up for deployments? When I get some time I can try and make an IAM user for you to deploy the backend, too. Ryan and I talked about setting up some time for us to meet and walk through the backend.

**Comment by chasdevs** [comment]
I'd say go ahead and merge this; test it if you can deploy but if not we'll find out soon enough.

**Comment by jamesmcnamara** [comment]
I don't THINK I've been set up for deployments yet; I haven't walked through that stuff yet.

However, I don't have write permissions on this repo, so I can't merge.

Maybe I should hold off on this until we get a chance to talk about the workflow?

**Comment by chasdevs** [comment]
Hmm you don't have write permissions for the repo?

**Comment by chasdevs** [comment]
I looked through and I don't see why you wouldn't. I'll merge this and when we talk about BE and FE we'll cover all these bases.

**Pull request merged**
